---
- name: creating variables
  hosts: all
  become: yes
  tasks:
    - name: creating directory
      ansible.builtin.file:
        path: "{{DIRECTORY}}"
        state: directory
    - name: creating file]
      ansible.builtin.file:
        path: "{{FILE}}"
        state: touch
    - name: creaging contend:
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRETORY}}/{{FILE}}"
        
     
