---
- name: Creating variables
  hosts: dev
  tasks:
    - name: Creating the directory
      ansible.builtin.file:
        path: "{{DIRECTORY}}"
        state: directory
    - name: Creating the file
      ansible.builtin.file:
        path: "{{FILE}}"
        state: touch
    - name: copy the content to the index.html
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"
