---
- name: Creating variables
  hosts: dev
  tasks:
    - name: create a directory
      ansible.builtin.file:
        path: "{{DIRECTORY}}"
        state: directory
    - name: create a file
      ansisble.builtin.file:
        path: "{{FILE}}"
        state: touch
    - name: copy the content to index.html
      ansible.builtin.copy:
        content: "{{CONTENT}}"
        dest: "{{DIRECTORY}}/{{FILE}}"
